### PR TITLE
Add job priority to the tile info summary

### PR DESCRIPTION
**Pull request by rivenwyrm**
Umm, sorry about the 2 commits, I just wanted the one that I had made for the job priority but now I'm not sure how to uh, 'clean up'. Let me know if you'd like me to go sort that out.

### CODE REVIEW

**Comment by Ext3h** [comment]
`git rebase -i` for rewriting the history in your own repository.

For pulling in changes from the main repository to your own repository, please use `git pull` or `git pull --rebase`, don't copy commits from the source repository as you did with c4551c6d85c (which now conflicts with 9d874f4cd02e you have copied it from).

**Comment by rivenwyrm** [comment]
> For pulling in changes from the main repository to your own repository, please use `git pull` or `git pull --rebase`, don't use a pull-request via github to copy commits from the source repository

Ah, sorry about that. Cleaned it up, I think it's good now.

**Comment by rivenwyrm** [comment]
> 
> 
> QString::number as used two lines above would have worked as well.

Ah, yes. Should I change that? Would save a #include and match nearby code better. Apparently I had my blinders on last night.

**Comment by Ext3h** [comment]
Yes, please fit to the surrounding code.

**Comment by rschurade** [comment]
Capture

Seems the priority goes to the wrong line.

**Pull request merged**
