### PR TITLE
Minor Farm/FarmField Optimizations

### PR DESCRIPTION
**Pull request by Utope**
QMaps value type "FarmField*" changed to "FarmField" avoiding some unnecessary
new/delete calls. Other minor optimizations/tweaks.

### CODE REVIEW

**Comment by Ext3h** [comment]
Looking good so far.

Just to make sure you are aware of it though, `QMap` as a container doesn't use move, but copy semantics. So this would break if `FarmField` had any non-copyable members.

**Comment by Utope** [comment]
Ah whoops your right didn't notice that. Thanks for pointing that out.

I was planning on replacing the QMap with a vector next so that should fix it.

Are there any restrictions against using std? or other standards that I should know about?

**Comment by Ext3h** [comment]
No restrictions on using `std`, except where objects need to pass the barrier between the simulation and the UI thread. Only Qt containers work at that spot.

`std::vector` would not be a good fit at all for that. You want a data structure with constant lookup time and compact allocation in these spots.

**Comment by Utope** [comment]
In the case where the number of elements is small a vector should perform better due to cache/data locality even though its Algorithmic time is technically worse. 99% of the interaction with m_fields is iterating over its members in the onTick function which vectors perform better at. We could also keep the list sorted allowing for better types of searches.

Also having a key of unsigned int helps alot because that comparison is very cheap.

**Comment by Utope** [comment]
Doesn't a vector have a much more compact allocation then a Map as well?

Btw I want to be clear that I'm not trying to be a dick or anything just trying to argue my side. Your the owner of this repo so you've got the final say.

**Comment by Ext3h** [comment]
For iteration, hash map (`QHash` or `std::unordered_map`) works just as fine in this scenario. Compared to a vector, the sparse allocation prevents vectorization, but that doesn't have much of an impact. The other possible impact is lack of order, which does have a significant impact when indexing into the world buffer by position. Had actually a couple of occurrences where an ordered set of positions was significantly faster merely due to that, despite the higher iteration cost.

Indexing by `Position` is actually faster than indexing by `Positon::toInt()`, as the later one forms an consecutive index into world sized buffers, while the overloaded hash function for positions is actually much simpler.

**Comment by Ext3h** [comment]
Not claiming you are wrong, just make sure to profile. The results are occasionally counterintuitive.

**Comment by Utope** [comment]
I Agree that replacing the QMap with a vector for the iteration would at most be a micro optimization in this scenario. 

You could keep the vector sorted by position in this scenario which should be similar to the Set scenario you just gave me If I'm understanding that correctly.

That Position thing is good to know! I'm very new to the code base so I'm still figuring stuff out!

Yea Profiling is really the only sure fire way to find out. I'll do some testing on that.

**Comment by Utope** [comment]
just did some profiling. I didn't test using a vector but the Map Iteration is so small compared to everything else it really doesn't matter. The main hog of the Farm::OnTick is a lot of Inventory::getClosestItem calls when there are tilled tiles with no jobs assigned. 

basically lots of tilled land with no seeds available.

**Pull request merged**
