### PR TITLE
SetApplicationResources + no default debug texts

### PR DESCRIPTION
**Pull request by Daynvheur**
The last ResourceDictionary set in the Xaml will override the game's language setting.
The game needs to be restarted to display language change.

### CODE REVIEW

**Comment by Ext3h** [comment]
This would break any visual editor for the XAML stuff, due to now (by default) unresolvable static resources.

**Review by Ext3h — CHANGES_REQUESTED** [review]
Need a solution which doesn't result in easily breaking workflows before we resume work on the translation subject.

Static resources are not getting us where we need to go, as this ends up breaking even basic Blend project etc.

**Review by Daynvheur — COMMENTED** [review]
There is the possibility to "find & replace" every occurence of `<!--<ResourceDictionary Source="localization/en_US.xaml" />-->` into `<ResourceDictionary Source="localization/en_US.xaml" />`.
Then "find & replace" the other way around. :)

**Comment by Daynvheur** [comment]
You're still able to copy-paste the code, if language is taken care of one day.

**Pull request closed without merging**
